# 本配置文件应当被导入到nacos中去
spring:

  application:
    name: demo

  # Spring服务需要数据库软件作为支撑
  # 这里定义的是一个默认的数据源，如果专用配置定义了别的数据源，则会使用后者
  datasource:
    url: jdbc:mysql://{你的数据库IP和端口号}/shiep?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {你的数据库账号}
    password: {你的数据库密码}

mybatis-plus:

  configuration:
    # 开启 SQL 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 驼峰命名自动映射
    map-underscore-to-camel-case: true

  global-config:
    db-config:
      # 逻辑删除字段名
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0