# 本配置文件应当被导入到nacos中去
spring:

  application:
    name: gateway

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # Spring服务需要数据库软件作为支撑
  # 这里定义的是一个默认的数据源，如果专用配置定义了别的数据源，则会使用后者
  datasource:
    url: jdbc:mysql://{你的数据库IP和端口号}/shiep?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: {你的数据库账号}
    password: {你的数据库密码}

  cloud:
    gateway:
      routes:
        #demo服务的代理
        - id: demo
          uri: lb://demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1

security:

  captcha:
    enabled: true
    type: math

  xss:
    enabled: true
    excludeUrls:

  ignore:
    whites:
      - /auth/**